### ISSUE TITLE
Issue when logging in

### ISSUE THREAD

**Issue by CatarinaGouveia** [neuralmagic/sparsify#274]
**Describe the bug**
When I try to run `sparsify.login api_token`. I'm getting the error below.

**Expected behavior**
Could you help me solve this? Thanks

**To Reproduce**
Exact steps to reproduce the behavior: 
```conda create -n sparsify-env
pip install sparsify.nighlty
pip install numpy==1.21.6
pip install sparsezoo==1.5.0
sparsify.login api_token
sparsify.run -h
```

**Errors**
```Traceback (most recent call last):
  File "/anaconda/envs/sparsify-env/bin/sparsify.run", line 5, in <module>
    from sparsify.cli.run import main
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsify/__init__.py", line 18, in <module>
    from .login import *
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsify/login.py", line 38, in <module>
    from sparsezoo.analyze.cli import CONTEXT_SETTINGS
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsezoo/__init__.py", line 20, in <module>
    from .model import *
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsezoo/model/__init__.py", line 17, in <module>
    from .model import *
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsezoo/model/model.py", line 22, in <module>
    from sparsezoo.analytics import sparsezoo_analytics
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsezoo/analytics.py", line 154, in <module>
    sparsezoo_analytics = GoogleAnalytics("sparsezoo", sparsezoo_version)
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsezoo/analytics.py", line 68, in __init__
    self._disabled = analytics_disabled()
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsezoo/analytics.py", line 43, in analytics_disabled
    return env_disabled or is_gdpr_country()
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsezoo/utils/gdpr.py", line 93, in is_gdpr_country
    country_code = get_country_code()
  File "/anaconda/envs/sparsify-env/lib/python3.8/site-packages/sparsezoo/utils/gdpr.py", line 79, in get_country_code
    geo = geocoder.ip(ip)
  File "/home/azureuser/.local/lib/python3.8/site-packages/geocoder/api.py", line 498, in ip
    return get(location, provider='ipinfo', **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/geocoder/api.py", line 198, in get
    return options[provider][method](location, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/geocoder/base.py", line 407, in __init__
    self._before_initialize(location, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/geocoder/ipinfo.py", line 80, in _before_initialize
    if location.lower() == 'me' or location == '':
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by CatarinaGouveia** [comment]
This was being caused by a wrong sparsezoo version (1.5.0)
